"""Generate conda activate/deactivate hooks for the parallel I/O stack.

The activation hook loads the MPI and NetCDF modules that the extensions were
built against and exports the matching build variables. The deactivation hook
restores the previous state exactly, unloading only the modules that the
activation hook itself loaded.

Replaces a nested bash heredoc; the quoting is far easier to keep correct here.
"""

from __future__ import annotations

import argparse
import re
import shlex
import stat
from pathlib import Path

HOOK_NAME = "mpi-netcdf.sh"

# Variables the activation hook overrides and the deactivation hook restores.
SAVED_VARS = (
    "HDF5_USE_FILE_LOCKING",
    "LD_LIBRARY_PATH",
    "PATH",
    "HDF5_INCDIR",
    "HDF5_INCLUDEDIR",
    "HDF5_PKGCONFIG_NAME",
    "HDF5_LIBDIR",
    "MPI4PY_BUILD_MPICC",
    "HDF5_DIR",
    "NETCDF4_DIR",
)


def sanitize(env_name: str) -> str:
    """Return env_name as a valid uppercase shell-variable fragment."""
    return re.sub(r"[^A-Z0-9]", "_", env_name.upper())


def save_block(prefix: str, var: str) -> str:
    """Emit bash that records whether var was set, and its value."""
    return f"""if [[ ${{{var}+x}} ]]; then
    _{prefix}_HAD_{var}=1
    _{prefix}_OLD_{var}="${{{var}}}"
else
    _{prefix}_HAD_{var}=0
    _{prefix}_OLD_{var}=""
fi
"""


def restore_block(prefix: str, var: str) -> str:
    """Emit bash that restores var to its recorded set/unset state."""
    return f"""if [[ "${{_{prefix}_HAD_{var}:-0}}" == "1" ]]; then
    export {var}="${{_{prefix}_OLD_{var}-}}"
else
    unset {var}
fi
"""


def load_block(prefix: str, kind: str) -> str:
    """Emit bash that loads one module unless it is already loaded."""
    module_var = f"_{prefix}_{kind}_MODULE"
    flag_var = f"_{prefix}_LOADED_{kind}"
    return f"""{flag_var}=0
if [[ -n "${{{module_var}}}" && ":${{LOADEDMODULES:-}}:" != *":${{{module_var}}}:"* ]]; then
    if module load "${{{module_var}}}"; then
        {flag_var}=1
    else
        printf 'ERROR: failed to load module: %s\\n' "${{{module_var}}}" >&2
        return 1 2>/dev/null || exit 1
    fi
fi
"""


def unload_block(prefix: str, kind: str) -> str:
    """Emit bash that unloads a module only if this hook loaded it."""
    module_var = f"_{prefix}_{kind}_MODULE"
    flag_var = f"_{prefix}_LOADED_{kind}"
    return f"""if [[ "${{{flag_var}:-0}}" == "1" && -n "${{{module_var}:-}}" ]]; then
    module unload "${{{module_var}}}" >/dev/null 2>&1 || true
fi
"""


def activate_hook(
    prefix: str,
    mpi_module: str,
    netcdf_module: str,
    hdf5_dir: str,
    netcdf4_dir: str,
    hdf5_libdir: str,
    mpicc: str,
    library_path: str,
) -> str:
    saves = "\n".join(save_block(prefix, var) for var in SAVED_VARS)
    loads = "\n".join(load_block(prefix, kind) for kind in ("MPI", "NETCDF"))
    return f"""#!/usr/bin/env bash
# Generated by src/conda_hooks.py. Do not edit by hand.

_{prefix}_MPI_MODULE={shlex.quote(mpi_module)}
_{prefix}_NETCDF_MODULE={shlex.quote(netcdf_module)}

{saves}
if [[ -n "${{_{prefix}_MPI_MODULE}}" || -n "${{_{prefix}_NETCDF_MODULE}}" ]]; then
    if ! type module >/dev/null 2>&1; then
        printf 'ERROR: the module command is unavailable in this shell.\\n' >&2
        return 1 2>/dev/null || exit 1
    fi
fi

{loads}
# Applied after module loading so module init cannot overwrite them.
export HDF5_USE_FILE_LOCKING="FALSE"
export HDF5_DIR={shlex.quote(hdf5_dir)}
export NETCDF4_DIR={shlex.quote(netcdf4_dir)}
unset HDF5_INCDIR HDF5_INCLUDEDIR HDF5_LIBDIR HDF5_PKGCONFIG_NAME
export PATH={shlex.quote(str(Path(mpicc).parent))}:"${{PATH:-}}"
_{prefix}_LIBDIR={shlex.quote(library_path)}
_{prefix}_LDPATH="${{LD_LIBRARY_PATH:+:${{LD_LIBRARY_PATH}}}}"
export LD_LIBRARY_PATH="${{_{prefix}_LIBDIR}}${{_{prefix}_LDPATH}}"
unset _{prefix}_LDPATH
unset _{prefix}_LIBDIR

_{prefix}_MPICC={shlex.quote(mpicc)}
if [[ ! -x "${{_{prefix}_MPICC}}" ]]; then
    printf 'ERROR: the selected mpicc is unavailable.\\n' >&2
    unset _{prefix}_MPICC
    return 1 2>/dev/null || exit 1
fi
export MPI4PY_BUILD_MPICC="${{_{prefix}_MPICC}}"
unset _{prefix}_MPICC
"""


def deactivate_hook(prefix: str) -> str:
    unloads = "\n".join(unload_block(prefix, kind) for kind in ("NETCDF", "MPI"))
    restores = "\n".join(restore_block(prefix, var) for var in SAVED_VARS)
    state_vars = [f"_{prefix}_HAD_{var}" for var in SAVED_VARS]
    state_vars += [f"_{prefix}_OLD_{var}" for var in SAVED_VARS]
    state_vars += [f"_{prefix}_LOADED_{kind}" for kind in ("MPI", "NETCDF")]
    state_vars += [f"_{prefix}_{kind}_MODULE" for kind in ("MPI", "NETCDF")]
    unsets = "\n".join(f"unset {name}" for name in state_vars)
    return f"""#!/usr/bin/env bash
# Generated by src/conda_hooks.py. Do not edit by hand.

# Unload in reverse order, and only what the activation hook loaded.
{unloads}
{restores}
{unsets}
"""


def write_hook(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", required=True, type=Path, help="CONDA_PREFIX")
    parser.add_argument("--env-name", required=True)
    parser.add_argument("--mpi-module", required=True)
    parser.add_argument("--netcdf-module", required=True)
    parser.add_argument("--hdf5-dir", required=True)
    parser.add_argument("--netcdf4-dir", required=True)
    parser.add_argument("--hdf5-libdir", required=True)
    parser.add_argument("--mpicc", required=True)
    parser.add_argument("--library-path", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    prefix = sanitize(args.env_name)

    write_hook(
        args.prefix / "etc" / "conda" / "activate.d" / HOOK_NAME,
        activate_hook(
            prefix,
            args.mpi_module,
            args.netcdf_module,
            args.hdf5_dir,
            args.netcdf4_dir,
            args.hdf5_libdir,
            args.mpicc,
            args.library_path,
        ),
    )
    write_hook(
        args.prefix / "etc" / "conda" / "deactivate.d" / HOOK_NAME,
        deactivate_hook(prefix),
    )


if __name__ == "__main__":
    main()
